CREATE DATABASE authdb;
CREATE DATABASE athletedb;
CREATE DATABASE activitydb;
CREATE DATABASE aidb;
CREATE DATABASE nutritiondb;
CREATE DATABASE notificationdb;
CREATE DATABASE paymentdb;
CREATE DATABASE n8ndb;
