name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - activity-service
          - ai-service
          - api-gateway
          - athlete-service
          - auth-service
          - eureka-server
          - frontend
          - nutrition-service

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build \
            -f ${{ matrix.service }}/Dockerfile \
            -t my-image-name:${{ matrix.service }}-${GITHUB_SHA::7} \
            ${{ matrix.service }}
